[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.99"
log = "0.4.27"
rs4a-vapix = { git = "https://github.com/apljungquist/rs4acap.git" }
url = "2.5.7"

[workspace.package]
edition = "2021"
